// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module arp_server_arp_pkg_sender (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        arpSendGrat_V_V_dout,
        arpSendGrat_V_V_empty_n,
        arpSendGrat_V_V_read,
        arpRequestMetaFifo_V_V_dout,
        arpRequestMetaFifo_V_V_empty_n,
        arpRequestMetaFifo_V_V_read,
        arpReplyMetaFifo_V_dout,
        arpReplyMetaFifo_V_empty_n,
        arpReplyMetaFifo_V_read,
        arpDataOut_V_data_V_din,
        arpDataOut_V_data_V_full_n,
        arpDataOut_V_data_V_write,
        arpDataOut_V_keep_V_din,
        arpDataOut_V_keep_V_full_n,
        arpDataOut_V_keep_V_write,
        arpDataOut_V_last_V_din,
        arpDataOut_V_last_V_full_n,
        arpDataOut_V_last_V_write,
        myMacAddress_V,
        myIpAddress_V
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_pp0_stg0_fsm_0 = 1'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv48_0 = 48'b000000000000000000000000000000000000000000000000;
parameter    ap_const_lv16_5 = 16'b101;
parameter    ap_const_lv16_4 = 16'b100;
parameter    ap_const_lv16_3 = 16'b11;
parameter    ap_const_lv16_2 = 16'b10;
parameter    ap_const_lv16_1 = 16'b1;
parameter    ap_const_lv4_3 = 4'b11;
parameter    ap_const_lv4_F = 4'b1111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_2F = 32'b101111;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv48_FFFFFFFFFFFF = 48'b111111111111111111111111111111111111111111111111;
parameter    ap_const_lv48_20004060008 = 48'b100000000000000100000001100000000000001000;
parameter    ap_const_lv32_1000608 = 32'b1000000000000011000001000;
parameter    ap_const_lv16_200 = 16'b1000000000;
parameter    ap_const_lv48_10004060008 = 48'b10000000000000100000001100000000000001000;
parameter    ap_const_lv32_30 = 32'b110000;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_const_lv32_40 = 32'b1000000;
parameter    ap_const_lv32_4F = 32'b1001111;
parameter    ap_const_lv32_50 = 32'b1010000;
parameter    ap_const_lv32_5F = 32'b1011111;
parameter    ap_const_lv32_60 = 32'b1100000;
parameter    ap_const_lv32_67 = 32'b1100111;
parameter    ap_const_lv32_68 = 32'b1101000;
parameter    ap_const_lv32_6F = 32'b1101111;
parameter    ap_const_lv32_70 = 32'b1110000;
parameter    ap_const_lv32_9F = 32'b10011111;
parameter    ap_const_lv32_A0 = 32'b10100000;
parameter    ap_const_lv32_BF = 32'b10111111;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] arpSendGrat_V_V_dout;
input   arpSendGrat_V_V_empty_n;
output   arpSendGrat_V_V_read;
input  [31:0] arpRequestMetaFifo_V_V_dout;
input   arpRequestMetaFifo_V_V_empty_n;
output   arpRequestMetaFifo_V_V_read;
input  [191:0] arpReplyMetaFifo_V_dout;
input   arpReplyMetaFifo_V_empty_n;
output   arpReplyMetaFifo_V_read;
output  [63:0] arpDataOut_V_data_V_din;
input   arpDataOut_V_data_V_full_n;
output   arpDataOut_V_data_V_write;
output  [7:0] arpDataOut_V_keep_V_din;
input   arpDataOut_V_keep_V_full_n;
output   arpDataOut_V_keep_V_write;
output  [0:0] arpDataOut_V_last_V_din;
input   arpDataOut_V_last_V_full_n;
output   arpDataOut_V_last_V_write;
input  [47:0] myMacAddress_V;
input  [31:0] myIpAddress_V;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg arpSendGrat_V_V_read;
reg arpRequestMetaFifo_V_V_read;
reg arpReplyMetaFifo_V_read;
reg[63:0] arpDataOut_V_data_V_din;
reg[7:0] arpDataOut_V_keep_V_din;
reg[0:0] arpDataOut_V_last_V_din;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm = 1'b1;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_0;
reg    ap_sig_bdd_20;
wire    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
wire   [1:0] aps_fsmState_load_load_fu_568_p1;
wire   [0:0] tmp_nbreadreq_fu_242_p3;
wire   [0:0] tmp_1_nbreadreq_fu_250_p3;
wire   [0:0] tmp_2_nbreadreq_fu_258_p3;
reg    ap_sig_bdd_77;
wire    arpDataOut_V_data_V1_status;
reg   [1:0] aps_fsmState_load_reg_998;
reg    ap_sig_bdd_93;
reg   [1:0] aps_fsmState = 2'b00;
reg   [15:0] sendCount = 16'b0000000000000000;
reg   [31:0] replyMeta_protoAddrSrc_V = 32'b00000000000000000000000000000000;
reg   [31:0] inputIP_V = 32'b00000000000000000000000000000000;
reg   [47:0] replyMeta_srcMac_V = 48'b000000000000000000000000000000000000000000000000;
reg   [15:0] replyMeta_ethType_V = 16'b0000000000000000;
reg   [15:0] replyMeta_hwType_V = 16'b0000000000000000;
reg   [15:0] replyMeta_protoType_V = 16'b0000000000000000;
reg   [7:0] replyMeta_hwLen_V = 8'b00000000;
reg   [7:0] replyMeta_protoLen_V = 8'b00000000;
reg   [47:0] replyMeta_hwAddrSrc_V = 48'b000000000000000000000000000000000000000000000000;
wire   [63:0] p_Result_38_fu_595_p3;
wire   [15:0] sendCount_load_load_fu_572_p1;
wire   [63:0] p_Result_36_fu_607_p3;
wire   [63:0] p_Result_35_fu_615_p3;
wire   [63:0] p_Result_33_fu_627_p3;
wire   [63:0] p_Result_32_fu_635_p3;
wire   [63:0] p_Result_30_fu_647_p3;
wire   [63:0] p_Result_29_fu_665_p3;
wire   [63:0] p_Result_27_fu_681_p3;
wire   [63:0] p_Result_26_fu_689_p3;
wire   [63:0] p_Result_24_fu_713_p6;
wire   [63:0] p_Result_23_fu_735_p4;
wire   [63:0] p_Result_21_fu_753_p3;
wire   [63:0] p_Result_20_fu_771_p3;
wire   [63:0] p_Result_18_fu_783_p3;
wire   [63:0] p_Result_17_fu_791_p3;
wire   [63:0] p_Result_15_fu_803_p3;
wire   [63:0] p_Result_14_fu_811_p3;
wire   [63:0] p_Result_s_fu_823_p3;
wire   [0:0] ap_reg_phiprechg_tmp_last_V_2_reg_297pp0_it0;
reg   [0:0] ap_reg_phiprechg_tmp_last_V_2_reg_297pp0_it1;
wire   [3:0] ap_reg_phiprechg_tmp_keep_V_4_reg_327pp0_it0;
reg   [3:0] ap_reg_phiprechg_tmp_keep_V_4_reg_327pp0_it1;
wire   [63:0] ap_reg_phiprechg_tmp_data_V_2_reg_356pp0_it0;
reg   [63:0] ap_reg_phiprechg_tmp_data_V_2_reg_356pp0_it1;
wire   [0:0] ap_reg_phiprechg_tmp_last_V_1_reg_378pp0_it0;
reg   [0:0] ap_reg_phiprechg_tmp_last_V_1_reg_378pp0_it1;
wire   [3:0] ap_reg_phiprechg_tmp_keep_V_2_reg_408pp0_it0;
reg   [3:0] ap_reg_phiprechg_tmp_keep_V_2_reg_408pp0_it1;
wire   [63:0] ap_reg_phiprechg_tmp_data_V_1_reg_437pp0_it0;
reg   [63:0] ap_reg_phiprechg_tmp_data_V_1_reg_437pp0_it1;
wire   [0:0] ap_reg_phiprechg_tmp_last_V_reg_459pp0_it0;
reg   [0:0] ap_reg_phiprechg_tmp_last_V_reg_459pp0_it1;
wire   [3:0] ap_reg_phiprechg_tmp_keep_V_1_reg_489pp0_it0;
reg   [3:0] ap_reg_phiprechg_tmp_keep_V_1_reg_489pp0_it1;
wire   [63:0] ap_reg_phiprechg_tmp_data_V_reg_518pp0_it0;
reg   [63:0] ap_reg_phiprechg_tmp_data_V_reg_518pp0_it1;
reg    arpDataOut_V_data_V1_update;
wire  signed [7:0] tmp_keep_V_5_fu_983_p1;
wire  signed [7:0] tmp_keep_V_3_fu_988_p1;
wire  signed [7:0] tmp_keep_V_fu_993_p1;
wire   [15:0] grp_fu_557_p2;
wire   [47:0] tmp_6_fu_855_p1;
wire   [15:0] p_Result_37_fu_585_p4;
wire   [15:0] tmp_17_fu_603_p1;
wire   [31:0] grp_fu_547_p4;
wire   [15:0] tmp_16_fu_623_p1;
wire   [15:0] tmp_15_fu_643_p1;
wire   [15:0] p_Result_28_fu_655_p4;
wire   [15:0] tmp_14_fu_677_p1;
wire   [15:0] tmp_13_fu_709_p1;
wire   [15:0] tmp_12_fu_749_p1;
wire   [15:0] p_Result_19_fu_761_p4;
wire   [15:0] tmp_11_fu_779_p1;
wire   [15:0] tmp_10_fu_799_p1;
wire   [15:0] tmp_7_fu_819_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_sig_pprstidle_pp0;
reg    ap_sig_bdd_188;
reg    ap_sig_bdd_192;
reg    ap_sig_bdd_196;
reg    ap_sig_bdd_200;
reg    ap_sig_bdd_204;
reg    ap_sig_bdd_208;
reg    ap_sig_bdd_100;
reg    ap_sig_bdd_154;
reg    ap_sig_bdd_160;
reg    ap_sig_bdd_166;
reg    ap_sig_bdd_172;
reg    ap_sig_bdd_178;
reg    ap_sig_bdd_183;
reg    ap_sig_bdd_213;
reg    ap_sig_bdd_217;
reg    ap_sig_bdd_221;
reg    ap_sig_bdd_225;
reg    ap_sig_bdd_229;
reg    ap_sig_bdd_233;
reg    ap_sig_bdd_244;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_pp0_stg0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_100) begin
        if (ap_sig_bdd_208) begin
            ap_reg_phiprechg_tmp_data_V_1_reg_437pp0_it1 <= p_Result_21_fu_753_p3;
        end else if (ap_sig_bdd_204) begin
            ap_reg_phiprechg_tmp_data_V_1_reg_437pp0_it1 <= p_Result_23_fu_735_p4;
        end else if (ap_sig_bdd_200) begin
            ap_reg_phiprechg_tmp_data_V_1_reg_437pp0_it1 <= p_Result_24_fu_713_p6;
        end else if (ap_sig_bdd_196) begin
            ap_reg_phiprechg_tmp_data_V_1_reg_437pp0_it1 <= p_Result_26_fu_689_p3;
        end else if (ap_sig_bdd_192) begin
            ap_reg_phiprechg_tmp_data_V_1_reg_437pp0_it1 <= p_Result_27_fu_681_p3;
        end else if (ap_sig_bdd_188) begin
            ap_reg_phiprechg_tmp_data_V_1_reg_437pp0_it1 <= p_Result_29_fu_665_p3;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_tmp_data_V_1_reg_437pp0_it1 <= ap_reg_phiprechg_tmp_data_V_1_reg_437pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_100) begin
        if (ap_sig_bdd_183) begin
            ap_reg_phiprechg_tmp_data_V_2_reg_356pp0_it1 <= p_Result_30_fu_647_p3;
        end else if (ap_sig_bdd_178) begin
            ap_reg_phiprechg_tmp_data_V_2_reg_356pp0_it1 <= p_Result_32_fu_635_p3;
        end else if (ap_sig_bdd_172) begin
            ap_reg_phiprechg_tmp_data_V_2_reg_356pp0_it1 <= p_Result_33_fu_627_p3;
        end else if (ap_sig_bdd_166) begin
            ap_reg_phiprechg_tmp_data_V_2_reg_356pp0_it1 <= p_Result_35_fu_615_p3;
        end else if (ap_sig_bdd_160) begin
            ap_reg_phiprechg_tmp_data_V_2_reg_356pp0_it1 <= p_Result_36_fu_607_p3;
        end else if (ap_sig_bdd_154) begin
            ap_reg_phiprechg_tmp_data_V_2_reg_356pp0_it1 <= p_Result_38_fu_595_p3;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_tmp_data_V_2_reg_356pp0_it1 <= ap_reg_phiprechg_tmp_data_V_2_reg_356pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_100) begin
        if (ap_sig_bdd_233) begin
            ap_reg_phiprechg_tmp_data_V_reg_518pp0_it1 <= p_Result_s_fu_823_p3;
        end else if (ap_sig_bdd_229) begin
            ap_reg_phiprechg_tmp_data_V_reg_518pp0_it1 <= p_Result_14_fu_811_p3;
        end else if (ap_sig_bdd_225) begin
            ap_reg_phiprechg_tmp_data_V_reg_518pp0_it1 <= p_Result_15_fu_803_p3;
        end else if (ap_sig_bdd_221) begin
            ap_reg_phiprechg_tmp_data_V_reg_518pp0_it1 <= p_Result_17_fu_791_p3;
        end else if (ap_sig_bdd_217) begin
            ap_reg_phiprechg_tmp_data_V_reg_518pp0_it1 <= p_Result_18_fu_783_p3;
        end else if (ap_sig_bdd_213) begin
            ap_reg_phiprechg_tmp_data_V_reg_518pp0_it1 <= p_Result_20_fu_771_p3;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_tmp_data_V_reg_518pp0_it1 <= ap_reg_phiprechg_tmp_data_V_reg_518pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_4) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_3) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_2) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_1) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (ap_const_lv16_0 == sendCount_load_load_fu_572_p1) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2)))) begin
        ap_reg_phiprechg_tmp_keep_V_1_reg_489pp0_it1 <= ap_const_lv4_F;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_5) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2))) begin
        ap_reg_phiprechg_tmp_keep_V_1_reg_489pp0_it1 <= ap_const_lv4_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        ap_reg_phiprechg_tmp_keep_V_1_reg_489pp0_it1 <= ap_reg_phiprechg_tmp_keep_V_1_reg_489pp0_it0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_4) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_3) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_2) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_1) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (ap_const_lv16_0 == sendCount_load_load_fu_572_p1) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1)))) begin
        ap_reg_phiprechg_tmp_keep_V_2_reg_408pp0_it1 <= ap_const_lv4_F;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_5) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1))) begin
        ap_reg_phiprechg_tmp_keep_V_2_reg_408pp0_it1 <= ap_const_lv4_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        ap_reg_phiprechg_tmp_keep_V_2_reg_408pp0_it1 <= ap_reg_phiprechg_tmp_keep_V_2_reg_408pp0_it0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_4)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_3)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (ap_const_lv16_0 == sendCount_load_load_fu_572_p1)))) begin
        ap_reg_phiprechg_tmp_keep_V_4_reg_327pp0_it1 <= ap_const_lv4_F;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_5))) begin
        ap_reg_phiprechg_tmp_keep_V_4_reg_327pp0_it1 <= ap_const_lv4_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        ap_reg_phiprechg_tmp_keep_V_4_reg_327pp0_it1 <= ap_reg_phiprechg_tmp_keep_V_4_reg_327pp0_it0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_4) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_3) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_2) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_1) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (ap_const_lv16_0 == sendCount_load_load_fu_572_p1) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1)))) begin
        ap_reg_phiprechg_tmp_last_V_1_reg_378pp0_it1 <= ap_const_lv1_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_5) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1))) begin
        ap_reg_phiprechg_tmp_last_V_1_reg_378pp0_it1 <= ap_const_lv1_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        ap_reg_phiprechg_tmp_last_V_1_reg_378pp0_it1 <= ap_reg_phiprechg_tmp_last_V_1_reg_378pp0_it0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_4)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_3)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (ap_const_lv16_0 == sendCount_load_load_fu_572_p1)))) begin
        ap_reg_phiprechg_tmp_last_V_2_reg_297pp0_it1 <= ap_const_lv1_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_5))) begin
        ap_reg_phiprechg_tmp_last_V_2_reg_297pp0_it1 <= ap_const_lv1_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        ap_reg_phiprechg_tmp_last_V_2_reg_297pp0_it1 <= ap_reg_phiprechg_tmp_last_V_2_reg_297pp0_it0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_4) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_3) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_2) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_1) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (ap_const_lv16_0 == sendCount_load_load_fu_572_p1) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2)))) begin
        ap_reg_phiprechg_tmp_last_V_reg_459pp0_it1 <= ap_const_lv1_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_5) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2))) begin
        ap_reg_phiprechg_tmp_last_V_reg_459pp0_it1 <= ap_const_lv1_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        ap_reg_phiprechg_tmp_last_V_reg_459pp0_it1 <= ap_reg_phiprechg_tmp_last_V_reg_459pp0_it0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (aps_fsmState == ap_const_lv2_0) & ~(tmp_nbreadreq_fu_242_p3 == ap_const_lv1_0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        aps_fsmState <= ap_const_lv2_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (aps_fsmState == ap_const_lv2_0) & (tmp_nbreadreq_fu_242_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_1_nbreadreq_fu_250_p3) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        aps_fsmState <= ap_const_lv2_2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (aps_fsmState == ap_const_lv2_0) & (tmp_nbreadreq_fu_242_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_nbreadreq_fu_250_p3) & ~(ap_const_lv1_0 == tmp_2_nbreadreq_fu_258_p3) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        aps_fsmState <= ap_const_lv2_3;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_5)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_5) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_5) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2)))) begin
        aps_fsmState <= ap_const_lv2_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (aps_fsmState == ap_const_lv2_0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        sendCount <= ap_const_lv16_0;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2)))) begin
        sendCount <= grp_fu_557_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        aps_fsmState_load_reg_998 <= aps_fsmState;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (aps_fsmState == ap_const_lv2_0) & (tmp_nbreadreq_fu_242_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_1_nbreadreq_fu_250_p3) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        inputIP_V <= arpRequestMetaFifo_V_V_dout;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (aps_fsmState == ap_const_lv2_0) & ~(tmp_nbreadreq_fu_242_p3 == ap_const_lv1_0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        replyMeta_ethType_V <= {{arpReplyMetaFifo_V_dout[ap_const_lv32_3F : ap_const_lv32_30]}};
        replyMeta_hwAddrSrc_V <= {{arpReplyMetaFifo_V_dout[ap_const_lv32_9F : ap_const_lv32_70]}};
        replyMeta_hwLen_V <= {{arpReplyMetaFifo_V_dout[ap_const_lv32_67 : ap_const_lv32_60]}};
        replyMeta_hwType_V <= {{arpReplyMetaFifo_V_dout[ap_const_lv32_4F : ap_const_lv32_40]}};
        replyMeta_protoAddrSrc_V <= {{arpReplyMetaFifo_V_dout[ap_const_lv32_BF : ap_const_lv32_A0]}};
        replyMeta_protoLen_V <= {{arpReplyMetaFifo_V_dout[ap_const_lv32_6F : ap_const_lv32_68]}};
        replyMeta_protoType_V <= {{arpReplyMetaFifo_V_dout[ap_const_lv32_5F : ap_const_lv32_50]}};
        replyMeta_srcMac_V <= tmp_6_fu_855_p1;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_77 or ap_sig_bdd_93)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it1))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_77 or ap_sig_bdd_93)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_0 assign process. ///
always @ (ap_sig_bdd_20)
begin
    if (ap_sig_bdd_20) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_pprstidle_pp0 assign process. ///
always @ (ap_start or ap_reg_ppiten_pp0_it0)
begin
    if (((ap_const_logic_0 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_0 == ap_start))) begin
        ap_sig_pprstidle_pp0 = ap_const_logic_1;
    end else begin
        ap_sig_pprstidle_pp0 = ap_const_logic_0;
    end
end

/// arpDataOut_V_data_V1_update assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_77 or aps_fsmState_load_reg_998 or ap_sig_bdd_93)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (aps_fsmState_load_reg_998 == ap_const_lv2_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (aps_fsmState_load_reg_998 == ap_const_lv2_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (aps_fsmState_load_reg_998 == ap_const_lv2_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))))) begin
        arpDataOut_V_data_V1_update = ap_const_logic_1;
    end else begin
        arpDataOut_V_data_V1_update = ap_const_logic_0;
    end
end

/// arpDataOut_V_data_V_din assign process. ///
always @ (aps_fsmState_load_reg_998 or ap_reg_phiprechg_tmp_data_V_2_reg_356pp0_it1 or ap_reg_phiprechg_tmp_data_V_1_reg_437pp0_it1 or ap_reg_phiprechg_tmp_data_V_reg_518pp0_it1 or ap_sig_bdd_244)
begin
    if (ap_sig_bdd_244) begin
        if ((aps_fsmState_load_reg_998 == ap_const_lv2_2)) begin
            arpDataOut_V_data_V_din = ap_reg_phiprechg_tmp_data_V_reg_518pp0_it1;
        end else if ((aps_fsmState_load_reg_998 == ap_const_lv2_1)) begin
            arpDataOut_V_data_V_din = ap_reg_phiprechg_tmp_data_V_1_reg_437pp0_it1;
        end else if ((aps_fsmState_load_reg_998 == ap_const_lv2_3)) begin
            arpDataOut_V_data_V_din = ap_reg_phiprechg_tmp_data_V_2_reg_356pp0_it1;
        end else begin
            arpDataOut_V_data_V_din = 'bx;
        end
    end else begin
        arpDataOut_V_data_V_din = 'bx;
    end
end

/// arpDataOut_V_keep_V_din assign process. ///
always @ (aps_fsmState_load_reg_998 or tmp_keep_V_5_fu_983_p1 or tmp_keep_V_3_fu_988_p1 or tmp_keep_V_fu_993_p1 or ap_sig_bdd_244)
begin
    if (ap_sig_bdd_244) begin
        if ((aps_fsmState_load_reg_998 == ap_const_lv2_2)) begin
            arpDataOut_V_keep_V_din = tmp_keep_V_fu_993_p1;
        end else if ((aps_fsmState_load_reg_998 == ap_const_lv2_1)) begin
            arpDataOut_V_keep_V_din = tmp_keep_V_3_fu_988_p1;
        end else if ((aps_fsmState_load_reg_998 == ap_const_lv2_3)) begin
            arpDataOut_V_keep_V_din = tmp_keep_V_5_fu_983_p1;
        end else begin
            arpDataOut_V_keep_V_din = 'bx;
        end
    end else begin
        arpDataOut_V_keep_V_din = 'bx;
    end
end

/// arpDataOut_V_last_V_din assign process. ///
always @ (aps_fsmState_load_reg_998 or ap_reg_phiprechg_tmp_last_V_2_reg_297pp0_it1 or ap_reg_phiprechg_tmp_last_V_1_reg_378pp0_it1 or ap_reg_phiprechg_tmp_last_V_reg_459pp0_it1 or ap_sig_bdd_244)
begin
    if (ap_sig_bdd_244) begin
        if ((aps_fsmState_load_reg_998 == ap_const_lv2_2)) begin
            arpDataOut_V_last_V_din = ap_reg_phiprechg_tmp_last_V_reg_459pp0_it1;
        end else if ((aps_fsmState_load_reg_998 == ap_const_lv2_1)) begin
            arpDataOut_V_last_V_din = ap_reg_phiprechg_tmp_last_V_1_reg_378pp0_it1;
        end else if ((aps_fsmState_load_reg_998 == ap_const_lv2_3)) begin
            arpDataOut_V_last_V_din = ap_reg_phiprechg_tmp_last_V_2_reg_297pp0_it1;
        end else begin
            arpDataOut_V_last_V_din = 'bx;
        end
    end else begin
        arpDataOut_V_last_V_din = 'bx;
    end
end

/// arpReplyMetaFifo_V_read assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or tmp_nbreadreq_fu_242_p3 or ap_sig_bdd_77 or ap_sig_bdd_93 or aps_fsmState)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (aps_fsmState == ap_const_lv2_0) & ~(tmp_nbreadreq_fu_242_p3 == ap_const_lv1_0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        arpReplyMetaFifo_V_read = ap_const_logic_1;
    end else begin
        arpReplyMetaFifo_V_read = ap_const_logic_0;
    end
end

/// arpRequestMetaFifo_V_V_read assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or tmp_nbreadreq_fu_242_p3 or tmp_1_nbreadreq_fu_250_p3 or ap_sig_bdd_77 or ap_sig_bdd_93 or aps_fsmState)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (aps_fsmState == ap_const_lv2_0) & (tmp_nbreadreq_fu_242_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_1_nbreadreq_fu_250_p3) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        arpRequestMetaFifo_V_V_read = ap_const_logic_1;
    end else begin
        arpRequestMetaFifo_V_V_read = ap_const_logic_0;
    end
end

/// arpSendGrat_V_V_read assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or tmp_nbreadreq_fu_242_p3 or tmp_1_nbreadreq_fu_250_p3 or tmp_2_nbreadreq_fu_258_p3 or ap_sig_bdd_77 or ap_sig_bdd_93 or aps_fsmState)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (aps_fsmState == ap_const_lv2_0) & (tmp_nbreadreq_fu_242_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_nbreadreq_fu_250_p3) & ~(ap_const_lv1_0 == tmp_2_nbreadreq_fu_258_p3) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        arpSendGrat_V_V_read = ap_const_logic_1;
    end else begin
        arpSendGrat_V_V_read = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_done_reg or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_77 or ap_sig_bdd_93 or ap_sig_pprstidle_pp0)
begin
    case (ap_CS_fsm)
        ap_ST_pp0_stg0_fsm_0 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_reg_phiprechg_tmp_data_V_1_reg_437pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_data_V_2_reg_356pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_data_V_reg_518pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_keep_V_1_reg_489pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_keep_V_2_reg_408pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_keep_V_4_reg_327pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_last_V_1_reg_378pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_last_V_2_reg_297pp0_it0 = 'bx;
assign ap_reg_phiprechg_tmp_last_V_reg_459pp0_it0 = 'bx;
assign ap_reg_ppiten_pp0_it0 = ap_start;

/// ap_sig_bdd_100 assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_77 or ap_sig_bdd_93)
begin
    ap_sig_bdd_100 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))));
end

/// ap_sig_bdd_154 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_154 = ((aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_5));
end

/// ap_sig_bdd_160 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_160 = ((aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_4));
end

/// ap_sig_bdd_166 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_166 = ((aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_3));
end

/// ap_sig_bdd_172 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_172 = ((aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_2));
end

/// ap_sig_bdd_178 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_178 = ((aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (sendCount_load_load_fu_572_p1 == ap_const_lv16_1));
end

/// ap_sig_bdd_183 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_183 = ((aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_3) & (ap_const_lv16_0 == sendCount_load_load_fu_572_p1));
end

/// ap_sig_bdd_188 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_188 = ((sendCount_load_load_fu_572_p1 == ap_const_lv16_5) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1));
end

/// ap_sig_bdd_192 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_192 = ((sendCount_load_load_fu_572_p1 == ap_const_lv16_4) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1));
end

/// ap_sig_bdd_196 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_196 = ((sendCount_load_load_fu_572_p1 == ap_const_lv16_3) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1));
end

/// ap_sig_bdd_20 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_20 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_200 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_200 = ((sendCount_load_load_fu_572_p1 == ap_const_lv16_2) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1));
end

/// ap_sig_bdd_204 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_204 = ((sendCount_load_load_fu_572_p1 == ap_const_lv16_1) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1));
end

/// ap_sig_bdd_208 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_208 = ((ap_const_lv16_0 == sendCount_load_load_fu_572_p1) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_1));
end

/// ap_sig_bdd_213 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_213 = ((sendCount_load_load_fu_572_p1 == ap_const_lv16_5) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2));
end

/// ap_sig_bdd_217 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_217 = ((sendCount_load_load_fu_572_p1 == ap_const_lv16_4) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2));
end

/// ap_sig_bdd_221 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_221 = ((sendCount_load_load_fu_572_p1 == ap_const_lv16_3) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2));
end

/// ap_sig_bdd_225 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_225 = ((sendCount_load_load_fu_572_p1 == ap_const_lv16_2) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2));
end

/// ap_sig_bdd_229 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_229 = ((sendCount_load_load_fu_572_p1 == ap_const_lv16_1) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2));
end

/// ap_sig_bdd_233 assign process. ///
always @ (aps_fsmState_load_load_fu_568_p1 or sendCount_load_load_fu_572_p1)
begin
    ap_sig_bdd_233 = ((ap_const_lv16_0 == sendCount_load_load_fu_572_p1) & (aps_fsmState_load_load_fu_568_p1 == ap_const_lv2_2));
end

/// ap_sig_bdd_244 assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_77 or ap_sig_bdd_93)
begin
    ap_sig_bdd_244 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_77) | (ap_sig_bdd_93 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))));
end

/// ap_sig_bdd_77 assign process. ///
always @ (ap_start or ap_done_reg or arpSendGrat_V_V_empty_n or tmp_nbreadreq_fu_242_p3 or tmp_1_nbreadreq_fu_250_p3 or tmp_2_nbreadreq_fu_258_p3 or arpRequestMetaFifo_V_V_empty_n or arpReplyMetaFifo_V_empty_n or aps_fsmState)
begin
    ap_sig_bdd_77 = (((arpSendGrat_V_V_empty_n == ap_const_logic_0) & (aps_fsmState == ap_const_lv2_0) & (tmp_nbreadreq_fu_242_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_nbreadreq_fu_250_p3) & ~(ap_const_lv1_0 == tmp_2_nbreadreq_fu_258_p3)) | ((aps_fsmState == ap_const_lv2_0) & (tmp_nbreadreq_fu_242_p3 == ap_const_lv1_0) & (arpRequestMetaFifo_V_V_empty_n == ap_const_logic_0) & ~(ap_const_lv1_0 == tmp_1_nbreadreq_fu_250_p3)) | ((aps_fsmState == ap_const_lv2_0) & (arpReplyMetaFifo_V_empty_n == ap_const_logic_0) & ~(tmp_nbreadreq_fu_242_p3 == ap_const_lv1_0)) | (ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_93 assign process. ///
always @ (arpDataOut_V_data_V1_status or aps_fsmState_load_reg_998)
begin
    ap_sig_bdd_93 = (((arpDataOut_V_data_V1_status == ap_const_logic_0) & (aps_fsmState_load_reg_998 == ap_const_lv2_3)) | ((arpDataOut_V_data_V1_status == ap_const_logic_0) & (aps_fsmState_load_reg_998 == ap_const_lv2_1)) | ((arpDataOut_V_data_V1_status == ap_const_logic_0) & (aps_fsmState_load_reg_998 == ap_const_lv2_2)));
end
assign aps_fsmState_load_load_fu_568_p1 = aps_fsmState;
assign arpDataOut_V_data_V1_status = (arpDataOut_V_data_V_full_n & arpDataOut_V_keep_V_full_n & arpDataOut_V_last_V_full_n);
assign arpDataOut_V_data_V_write = arpDataOut_V_data_V1_update;
assign arpDataOut_V_keep_V_write = arpDataOut_V_data_V1_update;
assign arpDataOut_V_last_V_write = arpDataOut_V_data_V1_update;
assign grp_fu_547_p4 = {{myMacAddress_V[ap_const_lv32_2F : ap_const_lv32_10]}};
assign grp_fu_557_p2 = (sendCount + ap_const_lv16_1);
assign p_Result_14_fu_811_p3 = {{ap_const_lv32_1000608}, {grp_fu_547_p4}};
assign p_Result_15_fu_803_p3 = {{tmp_10_fu_799_p1}, {ap_const_lv48_10004060008}};
assign p_Result_17_fu_791_p3 = {{myIpAddress_V}, {grp_fu_547_p4}};
assign p_Result_18_fu_783_p3 = {{tmp_11_fu_779_p1}, {ap_const_lv48_0}};
assign p_Result_19_fu_761_p4 = {{inputIP_V[ap_const_lv32_1F : ap_const_lv32_10]}};
assign p_Result_20_fu_771_p3 = {{ap_const_lv48_0}, {p_Result_19_fu_761_p4}};
assign p_Result_21_fu_753_p3 = {{tmp_12_fu_749_p1}, {replyMeta_srcMac_V}};
assign p_Result_23_fu_735_p4 = {{{replyMeta_hwType_V}, {replyMeta_ethType_V}}, {grp_fu_547_p4}};
assign p_Result_24_fu_713_p6 = {{{{{tmp_13_fu_709_p1}, {ap_const_lv16_200}}, {replyMeta_protoLen_V}}, {replyMeta_hwLen_V}}, {replyMeta_protoType_V}};
assign p_Result_26_fu_689_p3 = {{myIpAddress_V}, {grp_fu_547_p4}};
assign p_Result_27_fu_681_p3 = {{tmp_14_fu_677_p1}, {replyMeta_hwAddrSrc_V}};
assign p_Result_28_fu_655_p4 = {{replyMeta_protoAddrSrc_V[ap_const_lv32_1F : ap_const_lv32_10]}};
assign p_Result_29_fu_665_p3 = {{ap_const_lv48_0}, {p_Result_28_fu_655_p4}};
assign p_Result_30_fu_647_p3 = {{tmp_15_fu_643_p1}, {ap_const_lv48_FFFFFFFFFFFF}};
assign p_Result_32_fu_635_p3 = {{ap_const_lv32_1000608}, {grp_fu_547_p4}};
assign p_Result_33_fu_627_p3 = {{tmp_16_fu_623_p1}, {ap_const_lv48_20004060008}};
assign p_Result_35_fu_615_p3 = {{myIpAddress_V}, {grp_fu_547_p4}};
assign p_Result_36_fu_607_p3 = {{tmp_17_fu_603_p1}, {ap_const_lv48_FFFFFFFFFFFF}};
assign p_Result_37_fu_585_p4 = {{myIpAddress_V[ap_const_lv32_1F : ap_const_lv32_10]}};
assign p_Result_38_fu_595_p3 = {{ap_const_lv48_0}, {p_Result_37_fu_585_p4}};
assign p_Result_s_fu_823_p3 = {{tmp_7_fu_819_p1}, {ap_const_lv48_FFFFFFFFFFFF}};
assign sendCount_load_load_fu_572_p1 = sendCount;
assign tmp_10_fu_799_p1 = myMacAddress_V[15:0];
assign tmp_11_fu_779_p1 = inputIP_V[15:0];
assign tmp_12_fu_749_p1 = myMacAddress_V[15:0];
assign tmp_13_fu_709_p1 = myMacAddress_V[15:0];
assign tmp_14_fu_677_p1 = replyMeta_protoAddrSrc_V[15:0];
assign tmp_15_fu_643_p1 = myMacAddress_V[15:0];
assign tmp_16_fu_623_p1 = myMacAddress_V[15:0];
assign tmp_17_fu_603_p1 = myIpAddress_V[15:0];
assign tmp_1_nbreadreq_fu_250_p3 = arpRequestMetaFifo_V_V_empty_n;
assign tmp_2_nbreadreq_fu_258_p3 = arpSendGrat_V_V_empty_n;
assign tmp_6_fu_855_p1 = arpReplyMetaFifo_V_dout[47:0];
assign tmp_7_fu_819_p1 = myMacAddress_V[15:0];
assign tmp_keep_V_3_fu_988_p1 = $signed(ap_reg_phiprechg_tmp_keep_V_2_reg_408pp0_it1);
assign tmp_keep_V_5_fu_983_p1 = $signed(ap_reg_phiprechg_tmp_keep_V_4_reg_327pp0_it1);
assign tmp_keep_V_fu_993_p1 = $signed(ap_reg_phiprechg_tmp_keep_V_1_reg_489pp0_it1);
assign tmp_nbreadreq_fu_242_p3 = arpReplyMetaFifo_V_empty_n;


endmodule //arp_server_arp_pkg_sender

