// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "ConvertWidthC.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic ConvertWidthC::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic ConvertWidthC::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> ConvertWidthC::ap_ST_fsm_state1 = "1";
const sc_lv<3> ConvertWidthC::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> ConvertWidthC::ap_ST_fsm_state4 = "100";
const sc_lv<32> ConvertWidthC::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool ConvertWidthC::ap_const_boolean_1 = true;
const sc_lv<32> ConvertWidthC::ap_const_lv32_1 = "1";
const bool ConvertWidthC::ap_const_boolean_0 = false;
const sc_lv<1> ConvertWidthC::ap_const_lv1_0 = "0";
const sc_lv<1> ConvertWidthC::ap_const_lv1_1 = "1";
const sc_lv<41> ConvertWidthC::ap_const_lv41_0 = "00000000000000000000000000000000000000000";
const sc_lv<9> ConvertWidthC::ap_const_lv9_0 = "000000000";
const sc_lv<7> ConvertWidthC::ap_const_lv7_0 = "0000000";
const sc_lv<41> ConvertWidthC::ap_const_lv41_1 = "1";
const sc_lv<32> ConvertWidthC::ap_const_lv32_2 = "10";

ConvertWidthC::ConvertWidthC(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_N_pipe_0_V_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( N_pipe_0_V_V_empty_n );

    SC_METHOD(thread_N_pipe_0_V_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( N_pipe_0_V_V_empty_n );

    SC_METHOD(thread_add_ln401_fu_171_p2);
    sensitive << ( indvar_flatten11_reg_129 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( c_pipes_0_V_V_empty_n );
    sensitive << ( c_pipes_1_V_V_empty_n );
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln401_reg_191 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( c_pipes_0_V_V_empty_n );
    sensitive << ( c_pipes_1_V_V_empty_n );
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln401_reg_191 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( c_pipes_0_V_V_empty_n );
    sensitive << ( c_pipes_1_V_V_empty_n );
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln401_reg_191 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( N_pipe_0_V_V_empty_n );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);
    sensitive << ( c_pipes_0_V_V_empty_n );
    sensitive << ( c_pipes_1_V_V_empty_n );
    sensitive << ( out_V_V_full_n );
    sensitive << ( icmp_ln401_reg_191 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln401_fu_166_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_bound4_fu_160_p2);
    sensitive << ( p_shl_fu_140_p3 );
    sensitive << ( p_shl14_fu_156_p1 );

    SC_METHOD(thread_c_pipes_0_V_V_blk_n);
    sensitive << ( c_pipes_0_V_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln401_reg_191 );

    SC_METHOD(thread_c_pipes_0_V_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln401_reg_191 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_c_pipes_1_V_V_blk_n);
    sensitive << ( c_pipes_1_V_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln401_reg_191 );

    SC_METHOD(thread_c_pipes_1_V_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln401_reg_191 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_icmp_ln401_fu_166_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten11_reg_129 );
    sensitive << ( bound4_reg_186 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_out_V_V_blk_n);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln401_reg_191 );

    SC_METHOD(thread_out_V_V_din);
    sensitive << ( c_pipes_0_V_V_dout );
    sensitive << ( c_pipes_1_V_V_dout );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln401_reg_191 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_out_V_V_write);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln401_reg_191 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_p_shl14_fu_156_p1);
    sensitive << ( tmp_fu_148_p3 );

    SC_METHOD(thread_p_shl_fu_140_p3);
    sensitive << ( N_pipe_0_V_V_dout );

    SC_METHOD(thread_tmp_fu_148_p3);
    sensitive << ( N_pipe_0_V_V_dout );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( N_pipe_0_V_V_empty_n );
    sensitive << ( icmp_ln401_fu_166_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "ConvertWidthC_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, N_pipe_0_V_V_dout, "(port)N_pipe_0_V_V_dout");
    sc_trace(mVcdFile, N_pipe_0_V_V_empty_n, "(port)N_pipe_0_V_V_empty_n");
    sc_trace(mVcdFile, N_pipe_0_V_V_read, "(port)N_pipe_0_V_V_read");
    sc_trace(mVcdFile, c_pipes_0_V_V_dout, "(port)c_pipes_0_V_V_dout");
    sc_trace(mVcdFile, c_pipes_0_V_V_empty_n, "(port)c_pipes_0_V_V_empty_n");
    sc_trace(mVcdFile, c_pipes_0_V_V_read, "(port)c_pipes_0_V_V_read");
    sc_trace(mVcdFile, c_pipes_1_V_V_dout, "(port)c_pipes_1_V_V_dout");
    sc_trace(mVcdFile, c_pipes_1_V_V_empty_n, "(port)c_pipes_1_V_V_empty_n");
    sc_trace(mVcdFile, c_pipes_1_V_V_read, "(port)c_pipes_1_V_V_read");
    sc_trace(mVcdFile, out_V_V_din, "(port)out_V_V_din");
    sc_trace(mVcdFile, out_V_V_full_n, "(port)out_V_V_full_n");
    sc_trace(mVcdFile, out_V_V_write, "(port)out_V_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, N_pipe_0_V_V_blk_n, "N_pipe_0_V_V_blk_n");
    sc_trace(mVcdFile, c_pipes_0_V_V_blk_n, "c_pipes_0_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln401_reg_191, "icmp_ln401_reg_191");
    sc_trace(mVcdFile, c_pipes_1_V_V_blk_n, "c_pipes_1_V_V_blk_n");
    sc_trace(mVcdFile, out_V_V_blk_n, "out_V_V_blk_n");
    sc_trace(mVcdFile, indvar_flatten11_reg_129, "indvar_flatten11_reg_129");
    sc_trace(mVcdFile, bound4_fu_160_p2, "bound4_fu_160_p2");
    sc_trace(mVcdFile, bound4_reg_186, "bound4_reg_186");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, icmp_ln401_fu_166_p2, "icmp_ln401_fu_166_p2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, add_ln401_fu_171_p2, "add_ln401_fu_171_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, tmp_fu_148_p3, "tmp_fu_148_p3");
    sc_trace(mVcdFile, p_shl_fu_140_p3, "p_shl_fu_140_p3");
    sc_trace(mVcdFile, p_shl14_fu_156_p1, "p_shl14_fu_156_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

ConvertWidthC::~ConvertWidthC() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void ConvertWidthC::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, N_pipe_0_V_V_empty_n.read())))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, N_pipe_0_V_V_empty_n.read())))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln401_fu_166_p2.read()))) {
        indvar_flatten11_reg_129 = add_ln401_fu_171_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, N_pipe_0_V_V_empty_n.read())))) {
        indvar_flatten11_reg_129 = ap_const_lv41_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, N_pipe_0_V_V_empty_n.read())))) {
        bound4_reg_186 = bound4_fu_160_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln401_reg_191 = icmp_ln401_fu_166_p2.read();
    }
}

void ConvertWidthC::thread_N_pipe_0_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        N_pipe_0_V_V_blk_n = N_pipe_0_V_V_empty_n.read();
    } else {
        N_pipe_0_V_V_blk_n = ap_const_logic_1;
    }
}

void ConvertWidthC::thread_N_pipe_0_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, N_pipe_0_V_V_empty_n.read())))) {
        N_pipe_0_V_V_read = ap_const_logic_1;
    } else {
        N_pipe_0_V_V_read = ap_const_logic_0;
    }
}

void ConvertWidthC::thread_add_ln401_fu_171_p2() {
    add_ln401_fu_171_p2 = (!indvar_flatten11_reg_129.read().is_01() || !ap_const_lv41_1.is_01())? sc_lv<41>(): (sc_biguint<41>(indvar_flatten11_reg_129.read()) + sc_biguint<41>(ap_const_lv41_1));
}

void ConvertWidthC::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void ConvertWidthC::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void ConvertWidthC::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[2];
}

void ConvertWidthC::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertWidthC::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, c_pipes_0_V_V_empty_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, c_pipes_1_V_V_empty_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read()))));
}

void ConvertWidthC::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, c_pipes_0_V_V_empty_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, c_pipes_1_V_V_empty_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read()))));
}

void ConvertWidthC::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, c_pipes_0_V_V_empty_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, c_pipes_1_V_V_empty_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read()))));
}

void ConvertWidthC::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, N_pipe_0_V_V_empty_n.read()));
}

void ConvertWidthC::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertWidthC::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = ((esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, c_pipes_0_V_V_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, c_pipes_1_V_V_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read())));
}

void ConvertWidthC::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln401_fu_166_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void ConvertWidthC::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void ConvertWidthC::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void ConvertWidthC::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void ConvertWidthC::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void ConvertWidthC::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void ConvertWidthC::thread_bound4_fu_160_p2() {
    bound4_fu_160_p2 = (!p_shl_fu_140_p3.read().is_01() || !p_shl14_fu_156_p1.read().is_01())? sc_lv<41>(): (sc_biguint<41>(p_shl_fu_140_p3.read()) - sc_biguint<41>(p_shl14_fu_156_p1.read()));
}

void ConvertWidthC::thread_c_pipes_0_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0))) {
        c_pipes_0_V_V_blk_n = c_pipes_0_V_V_empty_n.read();
    } else {
        c_pipes_0_V_V_blk_n = ap_const_logic_1;
    }
}

void ConvertWidthC::thread_c_pipes_0_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        c_pipes_0_V_V_read = ap_const_logic_1;
    } else {
        c_pipes_0_V_V_read = ap_const_logic_0;
    }
}

void ConvertWidthC::thread_c_pipes_1_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0))) {
        c_pipes_1_V_V_blk_n = c_pipes_1_V_V_empty_n.read();
    } else {
        c_pipes_1_V_V_blk_n = ap_const_logic_1;
    }
}

void ConvertWidthC::thread_c_pipes_1_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        c_pipes_1_V_V_read = ap_const_logic_1;
    } else {
        c_pipes_1_V_V_read = ap_const_logic_0;
    }
}

void ConvertWidthC::thread_icmp_ln401_fu_166_p2() {
    icmp_ln401_fu_166_p2 = (!indvar_flatten11_reg_129.read().is_01() || !bound4_reg_186.read().is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten11_reg_129.read() == bound4_reg_186.read());
}

void ConvertWidthC::thread_out_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0))) {
        out_V_V_blk_n = out_V_V_full_n.read();
    } else {
        out_V_V_blk_n = ap_const_logic_1;
    }
}

void ConvertWidthC::thread_out_V_V_din() {
    out_V_V_din = esl_concat<32,32>(c_pipes_1_V_V_dout.read(), c_pipes_0_V_V_dout.read());
}

void ConvertWidthC::thread_out_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln401_reg_191.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        out_V_V_write = ap_const_logic_1;
    } else {
        out_V_V_write = ap_const_logic_0;
    }
}

void ConvertWidthC::thread_p_shl14_fu_156_p1() {
    p_shl14_fu_156_p1 = esl_zext<41,39>(tmp_fu_148_p3.read());
}

void ConvertWidthC::thread_p_shl_fu_140_p3() {
    p_shl_fu_140_p3 = esl_concat<32,9>(N_pipe_0_V_V_dout.read(), ap_const_lv9_0);
}

void ConvertWidthC::thread_tmp_fu_148_p3() {
    tmp_fu_148_p3 = esl_concat<32,7>(N_pipe_0_V_V_dout.read(), ap_const_lv7_0);
}

void ConvertWidthC::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, N_pipe_0_V_V_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln401_fu_166_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln401_fu_166_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

