#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("lbus_0_data_V", 128, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("lbus_1_data_V", 128, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("lbus_2_data_V", 128, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("lbus_3_data_V", 128, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("lbus_0_ena_V", 1, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("lbus_1_ena_V", 1, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("lbus_2_ena_V", 1, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("lbus_3_ena_V", 1, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("lbus_0_sop_V", 1, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("lbus_1_sop_V", 1, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("lbus_2_sop_V", 1, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("lbus_3_sop_V", 1, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("lbus_0_eop_V", 1, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("lbus_1_eop_V", 1, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("lbus_2_eop_V", 1, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("lbus_3_eop_V", 1, hls_in, 15, "ap_none", "in_data", 1),
	Port_Property("lbus_0_err_V", 1, hls_in, 16, "ap_none", "in_data", 1),
	Port_Property("lbus_1_err_V", 1, hls_in, 17, "ap_none", "in_data", 1),
	Port_Property("lbus_2_err_V", 1, hls_in, 18, "ap_none", "in_data", 1),
	Port_Property("lbus_3_err_V", 1, hls_in, 19, "ap_none", "in_data", 1),
	Port_Property("lbus_0_mty_V", 4, hls_in, 20, "ap_none", "in_data", 1),
	Port_Property("lbus_1_mty_V", 4, hls_in, 21, "ap_none", "in_data", 1),
	Port_Property("lbus_2_mty_V", 4, hls_in, 22, "ap_none", "in_data", 1),
	Port_Property("lbus_3_mty_V", 4, hls_in, 23, "ap_none", "in_data", 1),
	Port_Property("lbus_fifo", 544, hls_out, 24, "ap_none", "out_data", 1),
	Port_Property("lbus_fifo_we_V", 1, hls_out, 25, "ap_none", "out_data", 1),
	Port_Property("lbus_fifo_pkt_end", 408, hls_out, 26, "ap_none", "out_data", 1),
	Port_Property("lbus_fifo_pkt_end_we_V", 1, hls_out, 27, "ap_none", "out_data", 1),
	Port_Property("error_V", 1, hls_out, 28, "ap_none", "out_data", 1),
};
const char* HLS_Design_Meta::dut_name = "lbus_fifo_write";
