#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("g2N_input_V_dout", 89, hls_in, 0, "ap_fifo", "fifo_data", 1),
	Port_Property("g2N_input_V_empty_n", 1, hls_in, 0, "ap_fifo", "fifo_status", 1),
	Port_Property("g2N_input_V_read", 1, hls_out, 0, "ap_fifo", "fifo_update", 1),
	Port_Property("g2N_output_V_din", 73, hls_out, 1, "ap_fifo", "fifo_data", 1),
	Port_Property("g2N_output_V_full_n", 1, hls_in, 1, "ap_fifo", "fifo_status", 1),
	Port_Property("g2N_output_V_write", 1, hls_out, 1, "ap_fifo", "fifo_update", 1),
	Port_Property("buffer_storage_A_V_address0", 9, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("buffer_storage_A_V_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("buffer_storage_A_V_d0", 64, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("buffer_storage_A_V_q0", 64, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("buffer_storage_A_V_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("buffer_storage_B_V_address0", 9, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("buffer_storage_B_V_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("buffer_storage_B_V_d0", 64, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("buffer_storage_B_V_q0", 64, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("buffer_storage_B_V_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("n2G_input_V_dout", 73, hls_in, 4, "ap_fifo", "fifo_data", 1),
	Port_Property("n2G_input_V_empty_n", 1, hls_in, 4, "ap_fifo", "fifo_status", 1),
	Port_Property("n2G_input_V_read", 1, hls_out, 4, "ap_fifo", "fifo_update", 1),
	Port_Property("n2G_output_V_din", 89, hls_out, 5, "ap_fifo", "fifo_data", 1),
	Port_Property("n2G_output_V_full_n", 1, hls_in, 5, "ap_fifo", "fifo_status", 1),
	Port_Property("n2G_output_V_write", 1, hls_out, 5, "ap_fifo", "fifo_update", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "galapagos_bridge";
