create_clock -period 3.333 [get_ports init_clk_p]
set_property -dict {PACKAGE_PIN J16  IOSTANDARD DIFF_POD12_DCI } [get_ports {init_clk_p[0]}]
set_property -dict {PACKAGE_PIN H16  IOSTANDARD DIFF_POD12_DCI } [get_ports {init_clk_n[0]}]

create_clock -period 6.400 [get_ports gt_1_ref_clk_p]
set_property PACKAGE_PIN T10 [get_ports gt_1_ref_clk_n]
set_property PACKAGE_PIN T11 [get_ports gt_1_ref_clk_p]

set_property PACKAGE_PIN U8  [get_ports {qsfp1_4x_gtx_n[0]}]
set_property PACKAGE_PIN U9  [get_ports {qsfp1_4x_gtx_p[0]}]
set_property PACKAGE_PIN U3  [get_ports {qsfp1_4x_grx_n[0]}]
set_property PACKAGE_PIN U4  [get_ports {qsfp1_4x_grx_p[0]}]
set_property PACKAGE_PIN T6  [get_ports {qsfp1_4x_gtx_n[1]}]
set_property PACKAGE_PIN T7  [get_ports {qsfp1_4x_gtx_p[1]}]
set_property PACKAGE_PIN T1  [get_ports {qsfp1_4x_grx_n[1]}]
set_property PACKAGE_PIN T2  [get_ports {qsfp1_4x_grx_p[1]}]
set_property PACKAGE_PIN R8  [get_ports {qsfp1_4x_gtx_n[2]}]
set_property PACKAGE_PIN R9  [get_ports {qsfp1_4x_gtx_p[2]}]
set_property PACKAGE_PIN R3  [get_ports {qsfp1_4x_grx_n[2]}]
set_property PACKAGE_PIN R4  [get_ports {qsfp1_4x_grx_p[2]}]
set_property PACKAGE_PIN P6  [get_ports {qsfp1_4x_gtx_n[3]}]
set_property PACKAGE_PIN P7  [get_ports {qsfp1_4x_gtx_p[3]}]
set_property PACKAGE_PIN P1  [get_ports {qsfp1_4x_grx_n[3]}]
set_property PACKAGE_PIN P2  [get_ports {qsfp1_4x_grx_p[3]}]