  shell shell_i
    (.rstn(rstn)
    ,.rstn300(rstn300)
    ,.CLK(CLK)
    ,.CLK300(CLK300)
    ,.gt_ref_clk_n(gt_1_ref_clk_n)
    ,.gt_ref_clk_p(gt_1_ref_clk_p)
    ,.init_clk_clk_n(init_clk_n)
    ,.init_clk_clk_p(init_clk_p)
    ,.qsfp1_4x_grx_n(qsfp1_4x_grx_n)
    ,.qsfp1_4x_grx_p(qsfp1_4x_grx_p)
    ,.qsfp1_4x_gtx_n(qsfp1_4x_gtx_n)
    ,.qsfp1_4x_gtx_p(qsfp1_4x_gtx_p)