#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axis_data_V", 512, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("s_axis_keep_V", 64, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("s_axis_last_V", 1, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("s_axis_valid_V", 1, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("lbus_0_data_V", 128, hls_out, 4, "ap_none", "out_data", 1),
	Port_Property("lbus_1_data_V", 128, hls_out, 5, "ap_none", "out_data", 1),
	Port_Property("lbus_2_data_V", 128, hls_out, 6, "ap_none", "out_data", 1),
	Port_Property("lbus_3_data_V", 128, hls_out, 7, "ap_none", "out_data", 1),
	Port_Property("lbus_0_ena_V", 1, hls_out, 8, "ap_none", "out_data", 1),
	Port_Property("lbus_1_ena_V", 1, hls_out, 9, "ap_none", "out_data", 1),
	Port_Property("lbus_2_ena_V", 1, hls_out, 10, "ap_none", "out_data", 1),
	Port_Property("lbus_3_ena_V", 1, hls_out, 11, "ap_none", "out_data", 1),
	Port_Property("lbus_0_sop_V", 1, hls_out, 12, "ap_none", "out_data", 1),
	Port_Property("lbus_1_sop_V", 1, hls_out, 13, "ap_none", "out_data", 1),
	Port_Property("lbus_2_sop_V", 1, hls_out, 14, "ap_none", "out_data", 1),
	Port_Property("lbus_3_sop_V", 1, hls_out, 15, "ap_none", "out_data", 1),
	Port_Property("lbus_0_eop_V", 1, hls_out, 16, "ap_none", "out_data", 1),
	Port_Property("lbus_1_eop_V", 1, hls_out, 17, "ap_none", "out_data", 1),
	Port_Property("lbus_2_eop_V", 1, hls_out, 18, "ap_none", "out_data", 1),
	Port_Property("lbus_3_eop_V", 1, hls_out, 19, "ap_none", "out_data", 1),
	Port_Property("lbus_0_err_V", 1, hls_out, 20, "ap_none", "out_data", 1),
	Port_Property("lbus_1_err_V", 1, hls_out, 21, "ap_none", "out_data", 1),
	Port_Property("lbus_2_err_V", 1, hls_out, 22, "ap_none", "out_data", 1),
	Port_Property("lbus_3_err_V", 1, hls_out, 23, "ap_none", "out_data", 1),
	Port_Property("lbus_0_mty_V", 4, hls_out, 24, "ap_none", "out_data", 1),
	Port_Property("lbus_1_mty_V", 4, hls_out, 25, "ap_none", "out_data", 1),
	Port_Property("lbus_2_mty_V", 4, hls_out, 26, "ap_none", "out_data", 1),
	Port_Property("lbus_3_mty_V", 4, hls_out, 27, "ap_none", "out_data", 1),
	Port_Property("lbus_ready_V", 1, hls_in, 28, "ap_none", "in_data", 1),
	Port_Property("axis_ready_V", 1, hls_out, 29, "ap_none", "out_data", 1),
};
const char* HLS_Design_Meta::dut_name = "axis2lbus";
