webtalk_init -webtalk_dir /home/tarafdar/workDir/test/galapagos/projects/hls4ml/1/1.sim/sim_1/behav/xsim/xsim.dir/top_sim_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 23 11:26:02 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174111048_179741397_210699440_801" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "73d6d33f-aa96-4f08-8bab-c047c6d5bce2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6b9f842949a442699de0b7761d25e73a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2637 v3 @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1197.368 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3438656 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "71.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "739248_KB" -context "xsim\\usage"
webtalk_transmit -clientid 669019019 -regid "174111048_179741397_210699440_801" -xml /home/tarafdar/workDir/test/galapagos/projects/hls4ml/1/1.sim/sim_1/behav/xsim/xsim.dir/top_sim_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/tarafdar/workDir/test/galapagos/projects/hls4ml/1/1.sim/sim_1/behav/xsim/xsim.dir/top_sim_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/tarafdar/workDir/test/galapagos/projects/hls4ml/1/1.sim/sim_1/behav/xsim/xsim.dir/top_sim_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
